name: Deploy to GitHub Page
on: [push]
jobs:
  build_latex_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Checkout github pages repo
        uses: actions/checkout@v2
        with:
          repository: JohnDing1995/JohnDing1995.github.io
          path: gh-page
      # - name: Compile LaTeX document
      #   uses: xu-cheng/latex-action@master
      #   with:
      #     root_file: thesis.tex
      - name: Copy compiled pdf
        run: |
            cp -rf thesis.pdf gh-page/files/thesis.pdf
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.GITHUB_ACTION_TOKEN }}
          external_repository: JohnDing1995/JohnDing1995.github.io
          publish_branch: master
          publish_dir: ./gh-page
          allow_empty_commit: true
          enable_jekyll: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
    